// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewLand struct {
	TokenID    int    `json:"tokenId"`
	Title      string `json:"title"`
	Size       int    `json:"size"`
	SizeUnit   string `json:"sizeUnit"`
	PostalCode int    `json:"postalCode"`
	Location   string `json:"location"`
}
