// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewLand struct {
	TokenID       int    `json:"tokenId"`
	PostalCode    int    `json:"postalCode"`
	SateliteImage string `json:"sateliteImage"`
	Location      string `json:"location"`
}
